name: Playwright Test

on:
  workflow_dispatch:

jobs:
  test1:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

#      - name: Upload screenshot
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: screenshots
#          path: '*.png'
